version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/mdzip-base-maven-plugin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/mdzip-process-sources-maven-plugin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/mdzip-validate-maven-plugin"
    schedule:
      interval: "weekly"
